// Generated by CoffeeScript 1.3.3
(function() {
  var authToken, authorizeApp, circle, fourSquareClientId, fourSquareSecret, fourSquareToken, getToken, mappingTasks, redirectUrl, request, searchRadius, token, tokenCheck;

  circle = '';

  token = '';

  authToken = 0;

  fourSquareToken = '';

  fourSquareClientId = '3ODULPRCZOZL43JVOBNUBAUPXD5MXKBX24DOUZYNO0V3SEUL';

  fourSquareSecret = 'MBM0IB0YS1JZB2QLZ3WZDHSZAC10JOO0JY4VGDOF0IU3E5AH';

  searchRadius = 1200;

  redirectUrl = 'http://localhost/development/happenings/index.html';

  authorizeApp = function(user, api) {
    var clientId, uri;
    if (api === 'foursquare') {
      uri = 'https://foursquare.com/oauth2/authenticate?client_id=' + clientId + '&response_type=token&redirect_uri=' + redirectUrl;
    } else {
      clientId = '5d1ba596dc034a7a8895e309f5f2452f';
      uri = 'https://instagram.com/oauth/authorize/?client_id=' + clientId + '&redirect_uri=' + redirectUrl + '&response_type=token';
    }
    return window.location.href = uri;
  };

  getToken = function(type) {
    if (type === 'fourSquare') {
      return window.location.href.split('#access_token=')[1];
    } else {
      return window.location.href.split('#access_token=')[1];
    }
  };

  tokenCheck = function() {
    if (window.location.href.indexOf('access_token') > 0) {
      return token = getToken();
    } else if (window.location.href.indexOf('access_token') > 0) {
      return fourSquareToken = getToken('fourSquare');
    } else {
      return authorizeApp('blah', 'foursquare');
    }
  };

  request = function(long, lat, clientId, photoLayer, venueLayer) {
    var uri;
    $.ajax({
      type: "GET",
      dataType: "jsonp",
      cache: false,
      url: 'https://api.foursquare.com/v2/venues/explore?ll=' + lat + ',' + long + '&radius=' + searchRadius + '&client_id=' + fourSquareClientId + '&client_secret=' + fourSquareSecret + '&v=20120726',
      success: function(venues) {
        var groups;
        venueLayer.clearLayers();
        groups = venues.response.groups[0].items;
        return _.each(groups, function(item) {
          var locationLat, locationLng, object, photoTemplate;
          locationLat = item.venue.location.lat;
          locationLng = item.venue.location.lng;
          object = new L.CircleMarker(new L.LatLng(locationLat, locationLng), {
            radius: 7,
            clickable: true,
            stroke: 0,
            fillOpacity: .5,
            color: '#3ea7d7'
          });
          photoTemplate = _.template($("#popupTemplate_venue").html(), {
            item: item
          });
          object.bindPopup(photoTemplate);
          return venueLayer.addLayer(object);
        });
      }
    });
    if (token) {
      uri = 'https://api.instagram.com/v1/media/search?lat=' + lat + '&lng=' + long + '&distance=' + searchRadius + '&access_token=' + token;
    } else {
      uri = 'https://api.instagram.com/v1/media/search?lat=' + lat + '&lng=' + long + '&distance=' + searchRadius + '&client_id=' + clientId;
    }
    return $.ajax({
      type: "GET",
      dataType: "jsonp",
      cache: false,
      url: uri,
      success: function(photos) {
        photoLayer.clearLayers();
        return _.each(photos.data, function(photo) {
          var object, photoTemplate;
          if (photo.location) {
            object = new L.CircleMarker(new L.LatLng(photo.location.latitude, photo.location.longitude), {
              radius: 7,
              clickable: true,
              stroke: 0,
              fillOpacity: .5,
              color: '#FF9933'
            });
            photoTemplate = _.template($("#popupTemplate").html(), {
              photo: photo
            });
            object.bindPopup(photoTemplate);
            return photoLayer.addLayer(object);
          }
        });
      }
    });
  };

  mappingTasks = function() {
    var clientId, map, onLocationError, onLocationFound, onMapClick, photoLayer, tiles, venueLayer;
    onLocationFound = function(e) {};
    onLocationError = function(e) {
      return map.setView(new L.LatLng(37.76745803822967, -122.45018005371094), 13).addLayer(tiles);
    };
    onMapClick = function(e) {
      var radius;
      if (!circle) {
        radius = parseInt(searchRadius + 500);
        circle = new L.Circle(e.latlng, radius, {
          color: '#919191',
          fill: true,
          fillOpacity: 0.1,
          weight: 1.5,
          clickable: false
        });
        map.addLayer(circle);
      } else {
        circle.setLatLng(e.latlng);
      }
      return request(+e.latlng.lng.toFixed(2), e.latlng.lat.toFixed(2), clientId, photoLayer, venueLayer);
    };
    map = new L.Map('map');
    tiles = new L.TileLayer('http://a.tiles.mapbox.com/v3/bobbysud.map-ez4mk2nl/{z}/{x}/{y}.png', {
      maxZoom: 17
    });
    photoLayer = new L.LayerGroup();
    venueLayer = new L.LayerGroup();
    clientId = 'f62cd3b9e9a54a8fb18f7e122abc52df';
    map.addLayer(tiles);
    map.on('locationfound', onLocationFound);
    map.on('locationerror', onLocationError);
    map.locateAndSetView(13);
    map.on('click', onMapClick);
    map.addLayer(photoLayer);
    map.addLayer(venueLayer);
    map.on("popupopen", function(e) {
      var date;
      date = new Date(parseInt($("#timeago").html()) * 1000);
      $('.leaflet-popup-pane').css({
        'opacity': 0,
        'margin-top': 0
      });
      $('#timeago').text($.timeago(date));
      return $('.leaflet-popup-pane').animate({
        opacity: 1,
        marginTop: '-5'
      }, 500, function() {});
    });
    return $('<div>zoom out</div>').addClass('zoom-out').attr('title', 'See somewhere other than San Francisco, the map demo capital of the world.').click(function() {
      return map.setView(new L.LatLng(40.84706035607122, -94.482421875), 4);
    }).appendTo($('#map'));
  };

  $(document).ready(function() {
    mappingTasks();
    if (authToken === 1) {
      return tokenCheck();
    }
  });

}).call(this);
